# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on: 
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt secret
      run: /bin/sh ./decryptFiles.sh
      env:
        GOOGLE_SERVICES_PASS_PHRASE: ${{ secrets.GOOGLE_SERVICES_PASS_PHRASE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile
      run: ./gradlew assembleDebug
    - name: Test
      run: ./gradlew test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DebugApk.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
